# Generated by Django 4.2.15 on 2025-04-24 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("examples", "0008_assignment"),
        ("projects", "0011_project_minpercentage"),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotationRule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(default="", max_length=255)),
                ("description", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="AnnotationRuleType",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("annotation_rule_type", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="VotingCofiguration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("voting_threshold", models.IntegerField(default=0)),
                ("percentage_threshold", models.FloatField(default=0.0)),
                ("begin_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                (
                    "annotation_rule_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voting_configurations",
                        to="projects.annotationruletype",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "example",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voting_configurations",
                        to="examples.example",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voting_configurations",
                        to="projects.project",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnnotationRuleAnswers",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("answer", models.BooleanField(default=False)),
                (
                    "annotation_rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_rule_answers",
                        to="projects.annotationrule",
                    ),
                ),
                (
                    "annotation_rule_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_rule_answers_set",
                        to="projects.annotationruletype",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="annotation_rule_answers",
                        to="projects.member",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="annotationrule",
            name="annotation_rule_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_rules_set",
                to="projects.annotationruletype",
            ),
        ),
        migrations.AddField(
            model_name="annotationrule",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="annotation_rules", to="projects.project"
            ),
        ),
        migrations.AddField(
            model_name="annotationrule",
            name="voting_configuration",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_rules",
                to="projects.votingcofiguration",
            ),
        ),
    ]
