# Generated by Django 4.2.15 on 2025-04-15 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0012_annotationrule_annotationruletype_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="annotationrule",
            name="annotation_rule_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_rules_set",
                to="projects.annotationruletype",
            ),
        ),
        migrations.AlterField(
            model_name="annotationruleanswers",
            name="annotation_rule_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="annotation_rule_answers_set",
                to="projects.annotationruletype",
            ),
        ),
    ]
