# Generated by Django 4.2.15 on 2025-04-29 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_annotationrule_final_result_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="votingcofiguration",
            name="example",
        ),
    ]
