# Generated by Django 4.2.15 on 2025-04-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0013_alter_annotationrule_annotation_rule_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="annotationrule",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
