# Generated by Django 4.2.15 on 2025-04-21 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("examples", "0008_assignment"),
        ("projects", "0014_annotationrule_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="votingcofiguration",
            name="example",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="voting_configurations",
                to="examples.example",
            ),
        ),
    ]
