# Generated by Django 4.2.15 on 2025-04-21 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0015_votingcofiguration_example"),
    ]

    operations = [
        migrations.AddField(
            model_name="votingcofiguration",
            name="boolean_threshold",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="votingcofiguration",
            name="percentage_threshold",
            field=models.FloatField(default=0.0),
        ),
    ]
