# Generated by Django 3.2.14 on 2023-09-15 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0015_question_answer_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.DeleteModel(
            name='QuestionType',
        ),
    ] 