# Generated by Django 4.2.15 on 2025-06-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_remove_question_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_type",
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
