# Generated by Django 4.2.15 on 2025-04-22 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0014_project_minpercentage_and_more"),
        ("projects", "0016_votingcofiguration_boolean_threshold_and_more"),
    ]

    operations = []
