# Generated by Django 4.2.15 on 2025-04-22 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0016_votingcofiguration_boolean_threshold_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="votingcofiguration",
            name="boolean_threshold",
        ),
    ]
