# Generated by Django 4.2.15 on 2025-04-22 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0017_merge_20250422_1504"),
        ("projects", "0017_remove_votingcofiguration_boolean_threshold"),
    ]

    operations = []
