# Generated by Django 4.2.15 on 2025-06-13 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0018_perspective_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotationrule",
            name="annotation_rule_type",
        ),
        migrations.RemoveField(
            model_name="annotationruleanswers",
            name="annotation_rule_type",
        ),
        migrations.RemoveField(
            model_name="votingcofiguration",
            name="annotation_rule_type",
        ),
    ]
