# Generated by Django 4.2.15 on 2025-06-13 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0019_remove_annotationrule_annotation_rule_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="votingcofiguration",
            name="is_closed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="votingcofiguration",
            name="version",
            field=models.IntegerField(default=1),
        ),
    ]
