# Generated by Django 4.2.15 on 2025-06-13 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_votingcofiguration_is_closed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perspective",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="perspectives", to="projects.project"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="votingcofiguration",
            unique_together={("project", "version")},
        ),
    ]
