# Generated by Django 4.2.15 on 2025-06-13 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0020_votingcofiguration_is_closed_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="votingcofiguration",
            unique_together={("project", "version")},
        ),
    ]
