# Generated by Django 4.2.15 on 2025-06-14 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_alter_perspective_project"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnnotationRuleType",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="answer_option",
        ),
        migrations.DeleteModel(
            name="OptionQuestion",
        ),
        migrations.DeleteModel(
            name="OptionsGroup",
        ),
    ]
