# Generated by Django 4.2.15 on 2025-06-13 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0021_alter_perspective_project_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="perspective",
            name="project",
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="projects.project"),
        ),
    ]
