# Generated by Django 4.2.15 on 2025-06-14 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0022_remove_question_options_group"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="annotationrule",
            name="description",
        ),
    ]
