# Generated by Django 4.2.15 on 2025-06-14 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0023_delete_annotationruletype_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AnnotationRuleType",
        ),
        migrations.RemoveField(
            model_name="annotationrule",
            name="description",
        ),
        migrations.RemoveField(
            model_name="answer",
            name="answer_option",
        ),
        migrations.RemoveField(
            model_name="question",
            name="options_group",
        ),
        migrations.DeleteModel(
            name="OptionQuestion",
        ),
        migrations.DeleteModel(
            name="OptionsGroup",
        ),
    ]
