# Generated by Django 4.2.15 on 2025-06-14 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0018_datasetreview"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datasetreview",
            name="comment",
            field=models.TextField(blank=True, help_text="Optional comment about the discrepancy", null=True),
        ),
    ]
