# Generated by Django 4.2.15 on 2025-06-15 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("labels", "0019_alter_datasetreview_comment"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ManualDiscrepancy",
        ),
    ]
